//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppWebTestPeople.ServiceReferencePerson {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PersonDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        private bool DeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleAppWebTestPeople.ServiceReferencePerson.PersonTypeDto PersonTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ConsoleAppWebTestPeople.ServiceReferencePerson.PersonTypeDto PersonType {
            get {
                return this.PersonTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonTypeField, value) != true)) {
                    this.PersonTypeField = value;
                    this.RaisePropertyChanged("PersonType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonTypeDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PersonTypeDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private byte IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePerson.WebPersonServiceSoap")]
    public interface WebPersonServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento personDto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        ConsoleAppWebTestPeople.ServiceReferencePerson.InsertResponse Insert(ConsoleAppWebTestPeople.ServiceReferencePerson.InsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppWebTestPeople.ServiceReferencePerson.InsertResponse> InsertAsync(ConsoleAppWebTestPeople.ServiceReferencePerson.InsertRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento personDto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        ConsoleAppWebTestPeople.ServiceReferencePerson.UpdateResponse Update(ConsoleAppWebTestPeople.ServiceReferencePerson.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppWebTestPeople.ServiceReferencePerson.UpdateResponse> UpdateAsync(ConsoleAppWebTestPeople.ServiceReferencePerson.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        void Delete(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteAsync(System.Guid id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        ConsoleAppWebTestPeople.ServiceReferencePerson.GetResponse Get(ConsoleAppWebTestPeople.ServiceReferencePerson.GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppWebTestPeople.ServiceReferencePerson.GetResponse> GetAsync(ConsoleAppWebTestPeople.ServiceReferencePerson.GetRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppWebTestPeople.ServiceReferencePerson.InsertRequestBody Body;
        
        public InsertRequest() {
        }
        
        public InsertRequest(ConsoleAppWebTestPeople.ServiceReferencePerson.InsertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleAppWebTestPeople.ServiceReferencePerson.PersonDto personDto;
        
        public InsertRequestBody() {
        }
        
        public InsertRequestBody(ConsoleAppWebTestPeople.ServiceReferencePerson.PersonDto personDto) {
            this.personDto = personDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppWebTestPeople.ServiceReferencePerson.InsertResponseBody Body;
        
        public InsertResponse() {
        }
        
        public InsertResponse(ConsoleAppWebTestPeople.ServiceReferencePerson.InsertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertResponseBody {
        
        public InsertResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppWebTestPeople.ServiceReferencePerson.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(ConsoleAppWebTestPeople.ServiceReferencePerson.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleAppWebTestPeople.ServiceReferencePerson.PersonDto personDto;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(ConsoleAppWebTestPeople.ServiceReferencePerson.PersonDto personDto) {
            this.personDto = personDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppWebTestPeople.ServiceReferencePerson.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(ConsoleAppWebTestPeople.ServiceReferencePerson.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateResponseBody {
        
        public UpdateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppWebTestPeople.ServiceReferencePerson.GetRequestBody Body;
        
        public GetRequest() {
        }
        
        public GetRequest(ConsoleAppWebTestPeople.ServiceReferencePerson.GetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid id;
        
        public GetRequestBody() {
        }
        
        public GetRequestBody(System.Guid id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppWebTestPeople.ServiceReferencePerson.GetResponseBody Body;
        
        public GetResponse() {
        }
        
        public GetResponse(ConsoleAppWebTestPeople.ServiceReferencePerson.GetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleAppWebTestPeople.ServiceReferencePerson.PersonDto GetResult;
        
        public GetResponseBody() {
        }
        
        public GetResponseBody(ConsoleAppWebTestPeople.ServiceReferencePerson.PersonDto GetResult) {
            this.GetResult = GetResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebPersonServiceSoapChannel : ConsoleAppWebTestPeople.ServiceReferencePerson.WebPersonServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebPersonServiceSoapClient : System.ServiceModel.ClientBase<ConsoleAppWebTestPeople.ServiceReferencePerson.WebPersonServiceSoap>, ConsoleAppWebTestPeople.ServiceReferencePerson.WebPersonServiceSoap {
        
        public WebPersonServiceSoapClient() {
        }
        
        public WebPersonServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebPersonServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebPersonServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebPersonServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppWebTestPeople.ServiceReferencePerson.InsertResponse ConsoleAppWebTestPeople.ServiceReferencePerson.WebPersonServiceSoap.Insert(ConsoleAppWebTestPeople.ServiceReferencePerson.InsertRequest request) {
            return base.Channel.Insert(request);
        }
        
        public void Insert(ConsoleAppWebTestPeople.ServiceReferencePerson.PersonDto personDto) {
            ConsoleAppWebTestPeople.ServiceReferencePerson.InsertRequest inValue = new ConsoleAppWebTestPeople.ServiceReferencePerson.InsertRequest();
            inValue.Body = new ConsoleAppWebTestPeople.ServiceReferencePerson.InsertRequestBody();
            inValue.Body.personDto = personDto;
            ConsoleAppWebTestPeople.ServiceReferencePerson.InsertResponse retVal = ((ConsoleAppWebTestPeople.ServiceReferencePerson.WebPersonServiceSoap)(this)).Insert(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleAppWebTestPeople.ServiceReferencePerson.InsertResponse> ConsoleAppWebTestPeople.ServiceReferencePerson.WebPersonServiceSoap.InsertAsync(ConsoleAppWebTestPeople.ServiceReferencePerson.InsertRequest request) {
            return base.Channel.InsertAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppWebTestPeople.ServiceReferencePerson.InsertResponse> InsertAsync(ConsoleAppWebTestPeople.ServiceReferencePerson.PersonDto personDto) {
            ConsoleAppWebTestPeople.ServiceReferencePerson.InsertRequest inValue = new ConsoleAppWebTestPeople.ServiceReferencePerson.InsertRequest();
            inValue.Body = new ConsoleAppWebTestPeople.ServiceReferencePerson.InsertRequestBody();
            inValue.Body.personDto = personDto;
            return ((ConsoleAppWebTestPeople.ServiceReferencePerson.WebPersonServiceSoap)(this)).InsertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppWebTestPeople.ServiceReferencePerson.UpdateResponse ConsoleAppWebTestPeople.ServiceReferencePerson.WebPersonServiceSoap.Update(ConsoleAppWebTestPeople.ServiceReferencePerson.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public void Update(ConsoleAppWebTestPeople.ServiceReferencePerson.PersonDto personDto) {
            ConsoleAppWebTestPeople.ServiceReferencePerson.UpdateRequest inValue = new ConsoleAppWebTestPeople.ServiceReferencePerson.UpdateRequest();
            inValue.Body = new ConsoleAppWebTestPeople.ServiceReferencePerson.UpdateRequestBody();
            inValue.Body.personDto = personDto;
            ConsoleAppWebTestPeople.ServiceReferencePerson.UpdateResponse retVal = ((ConsoleAppWebTestPeople.ServiceReferencePerson.WebPersonServiceSoap)(this)).Update(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleAppWebTestPeople.ServiceReferencePerson.UpdateResponse> ConsoleAppWebTestPeople.ServiceReferencePerson.WebPersonServiceSoap.UpdateAsync(ConsoleAppWebTestPeople.ServiceReferencePerson.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppWebTestPeople.ServiceReferencePerson.UpdateResponse> UpdateAsync(ConsoleAppWebTestPeople.ServiceReferencePerson.PersonDto personDto) {
            ConsoleAppWebTestPeople.ServiceReferencePerson.UpdateRequest inValue = new ConsoleAppWebTestPeople.ServiceReferencePerson.UpdateRequest();
            inValue.Body = new ConsoleAppWebTestPeople.ServiceReferencePerson.UpdateRequestBody();
            inValue.Body.personDto = personDto;
            return ((ConsoleAppWebTestPeople.ServiceReferencePerson.WebPersonServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        public void Delete(System.Guid id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(System.Guid id) {
            return base.Channel.DeleteAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppWebTestPeople.ServiceReferencePerson.GetResponse ConsoleAppWebTestPeople.ServiceReferencePerson.WebPersonServiceSoap.Get(ConsoleAppWebTestPeople.ServiceReferencePerson.GetRequest request) {
            return base.Channel.Get(request);
        }
        
        public ConsoleAppWebTestPeople.ServiceReferencePerson.PersonDto Get(System.Guid id) {
            ConsoleAppWebTestPeople.ServiceReferencePerson.GetRequest inValue = new ConsoleAppWebTestPeople.ServiceReferencePerson.GetRequest();
            inValue.Body = new ConsoleAppWebTestPeople.ServiceReferencePerson.GetRequestBody();
            inValue.Body.id = id;
            ConsoleAppWebTestPeople.ServiceReferencePerson.GetResponse retVal = ((ConsoleAppWebTestPeople.ServiceReferencePerson.WebPersonServiceSoap)(this)).Get(inValue);
            return retVal.Body.GetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleAppWebTestPeople.ServiceReferencePerson.GetResponse> ConsoleAppWebTestPeople.ServiceReferencePerson.WebPersonServiceSoap.GetAsync(ConsoleAppWebTestPeople.ServiceReferencePerson.GetRequest request) {
            return base.Channel.GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppWebTestPeople.ServiceReferencePerson.GetResponse> GetAsync(System.Guid id) {
            ConsoleAppWebTestPeople.ServiceReferencePerson.GetRequest inValue = new ConsoleAppWebTestPeople.ServiceReferencePerson.GetRequest();
            inValue.Body = new ConsoleAppWebTestPeople.ServiceReferencePerson.GetRequestBody();
            inValue.Body.id = id;
            return ((ConsoleAppWebTestPeople.ServiceReferencePerson.WebPersonServiceSoap)(this)).GetAsync(inValue);
        }
    }
}
