//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univalle.Fie.Sistemas.Unibook.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculty
    {
        public Faculty()
        {
            this.Career = new HashSet<Career>();
        }
    
        public short FacultyId { get; set; }
        public string Name { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ICollection<Career> Career { get; set; }
    }
}
