//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryEnterDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CategoryEnterDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private bool DeletedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebCategoryService.WebCategoryServiceSoap")]
    public interface WebCategoryServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento category del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.InsertResponse Insert(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.InsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        System.Threading.Tasks.Task<Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.InsertResponse> InsertAsync(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.InsertRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento category del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.UpdateResponse Update(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.UpdateResponse> UpdateAsync(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetDtoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDto", ReplyAction="*")]
        Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetDtoResponse GetDto(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetDtoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDto", ReplyAction="*")]
        System.Threading.Tasks.Task<Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetDtoResponse> GetDtoAsync(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetDtoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetResponse Get(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        System.Threading.Tasks.Task<Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetResponse> GetAsync(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert", Namespace="http://tempuri.org/", Order=0)]
        public Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.InsertRequestBody Body;
        
        public InsertRequest() {
        }
        
        public InsertRequest(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.InsertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.CategoryEnterDto category;
        
        public InsertRequestBody() {
        }
        
        public InsertRequestBody(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.CategoryEnterDto category) {
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertResponse", Namespace="http://tempuri.org/", Order=0)]
        public Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.InsertResponseBody Body;
        
        public InsertResponse() {
        }
        
        public InsertResponse(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.InsertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertResponseBody {
        
        public InsertResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.CategoryEnterDto category;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.CategoryEnterDto category) {
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateResponseBody {
        
        public UpdateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDtoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDto", Namespace="http://tempuri.org/", Order=0)]
        public Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetDtoRequestBody Body;
        
        public GetDtoRequest() {
        }
        
        public GetDtoRequest(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetDtoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDtoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetDtoRequestBody() {
        }
        
        public GetDtoRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDtoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDtoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetDtoResponseBody Body;
        
        public GetDtoResponse() {
        }
        
        public GetDtoResponse(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetDtoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDtoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.CategoryEnterDto GetDtoResult;
        
        public GetDtoResponseBody() {
        }
        
        public GetDtoResponseBody(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.CategoryEnterDto GetDtoResult) {
            this.GetDtoResult = GetDtoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get", Namespace="http://tempuri.org/", Order=0)]
        public Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetRequestBody Body;
        
        public GetRequest() {
        }
        
        public GetRequest(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRequestBody {
        
        public GetRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResponse", Namespace="http://tempuri.org/", Order=0)]
        public Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetResponseBody Body;
        
        public GetResponse() {
        }
        
        public GetResponse(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.CategoryEnterDto[] GetResult;
        
        public GetResponseBody() {
        }
        
        public GetResponseBody(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.CategoryEnterDto[] GetResult) {
            this.GetResult = GetResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebCategoryServiceSoapChannel : Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.WebCategoryServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebCategoryServiceSoapClient : System.ServiceModel.ClientBase<Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.WebCategoryServiceSoap>, Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.WebCategoryServiceSoap {
        
        public WebCategoryServiceSoapClient() {
        }
        
        public WebCategoryServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebCategoryServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebCategoryServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebCategoryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.InsertResponse Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.WebCategoryServiceSoap.Insert(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.InsertRequest request) {
            return base.Channel.Insert(request);
        }
        
        public void Insert(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.CategoryEnterDto category) {
            Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.InsertRequest inValue = new Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.InsertRequest();
            inValue.Body = new Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.InsertRequestBody();
            inValue.Body.category = category;
            Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.InsertResponse retVal = ((Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.WebCategoryServiceSoap)(this)).Insert(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.InsertResponse> Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.WebCategoryServiceSoap.InsertAsync(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.InsertRequest request) {
            return base.Channel.InsertAsync(request);
        }
        
        public System.Threading.Tasks.Task<Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.InsertResponse> InsertAsync(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.CategoryEnterDto category) {
            Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.InsertRequest inValue = new Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.InsertRequest();
            inValue.Body = new Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.InsertRequestBody();
            inValue.Body.category = category;
            return ((Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.WebCategoryServiceSoap)(this)).InsertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.UpdateResponse Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.WebCategoryServiceSoap.Update(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public void Update(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.CategoryEnterDto category) {
            Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.UpdateRequest inValue = new Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.UpdateRequest();
            inValue.Body = new Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.UpdateRequestBody();
            inValue.Body.category = category;
            Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.UpdateResponse retVal = ((Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.WebCategoryServiceSoap)(this)).Update(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.UpdateResponse> Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.WebCategoryServiceSoap.UpdateAsync(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.UpdateResponse> UpdateAsync(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.CategoryEnterDto category) {
            Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.UpdateRequest inValue = new Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.UpdateRequest();
            inValue.Body = new Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.UpdateRequestBody();
            inValue.Body.category = category;
            return ((Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.WebCategoryServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetDtoResponse Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.WebCategoryServiceSoap.GetDto(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetDtoRequest request) {
            return base.Channel.GetDto(request);
        }
        
        public Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.CategoryEnterDto GetDto(int id) {
            Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetDtoRequest inValue = new Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetDtoRequest();
            inValue.Body = new Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetDtoRequestBody();
            inValue.Body.id = id;
            Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetDtoResponse retVal = ((Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.WebCategoryServiceSoap)(this)).GetDto(inValue);
            return retVal.Body.GetDtoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetDtoResponse> Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.WebCategoryServiceSoap.GetDtoAsync(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetDtoRequest request) {
            return base.Channel.GetDtoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetDtoResponse> GetDtoAsync(int id) {
            Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetDtoRequest inValue = new Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetDtoRequest();
            inValue.Body = new Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetDtoRequestBody();
            inValue.Body.id = id;
            return ((Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.WebCategoryServiceSoap)(this)).GetDtoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetResponse Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.WebCategoryServiceSoap.Get(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetRequest request) {
            return base.Channel.Get(request);
        }
        
        public Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.CategoryEnterDto[] Get() {
            Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetRequest inValue = new Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetRequest();
            inValue.Body = new Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetRequestBody();
            Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetResponse retVal = ((Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.WebCategoryServiceSoap)(this)).Get(inValue);
            return retVal.Body.GetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetResponse> Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.WebCategoryServiceSoap.GetAsync(Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetRequest request) {
            return base.Channel.GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetResponse> GetAsync() {
            Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetRequest inValue = new Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetRequest();
            inValue.Body = new Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.GetRequestBody();
            return ((Univalle.Fie.Sistemas.UniBook.UsersTest.WebCategoryService.WebCategoryServiceSoap)(this)).GetAsync(inValue);
        }
    }
}
