//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PublicationMatterCareerFacultyDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PublicationMatterCareerFacultyDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PublicationMatterCareerFacultyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.PublicationAcademicDto PublicationAcademicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.SubjectDto SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.CareerDto CareerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.FacultyDto FacultyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PublicationMatterCareerFacultyId {
            get {
                return this.PublicationMatterCareerFacultyIdField;
            }
            set {
                if ((this.PublicationMatterCareerFacultyIdField.Equals(value) != true)) {
                    this.PublicationMatterCareerFacultyIdField = value;
                    this.RaisePropertyChanged("PublicationMatterCareerFacultyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.PublicationAcademicDto PublicationAcademic {
            get {
                return this.PublicationAcademicField;
            }
            set {
                if ((object.ReferenceEquals(this.PublicationAcademicField, value) != true)) {
                    this.PublicationAcademicField = value;
                    this.RaisePropertyChanged("PublicationAcademic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.SubjectDto Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.CareerDto Career {
            get {
                return this.CareerField;
            }
            set {
                if ((object.ReferenceEquals(this.CareerField, value) != true)) {
                    this.CareerField = value;
                    this.RaisePropertyChanged("Career");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.FacultyDto Faculty {
            get {
                return this.FacultyField;
            }
            set {
                if ((object.ReferenceEquals(this.FacultyField, value) != true)) {
                    this.FacultyField = value;
                    this.RaisePropertyChanged("Faculty");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PublicationAcademicDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PublicationAcademicDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long PublicationAcademicIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        private System.DateTime DatePublicationField;
        
        private bool DeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.CategoryAcademicDto CategoryAcademicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UserDto UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long PublicationAcademicId {
            get {
                return this.PublicationAcademicIdField;
            }
            set {
                if ((this.PublicationAcademicIdField.Equals(value) != true)) {
                    this.PublicationAcademicIdField = value;
                    this.RaisePropertyChanged("PublicationAcademicId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DatePublication {
            get {
                return this.DatePublicationField;
            }
            set {
                if ((this.DatePublicationField.Equals(value) != true)) {
                    this.DatePublicationField = value;
                    this.RaisePropertyChanged("DatePublication");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.CategoryAcademicDto CategoryAcademic {
            get {
                return this.CategoryAcademicField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryAcademicField, value) != true)) {
                    this.CategoryAcademicField = value;
                    this.RaisePropertyChanged("CategoryAcademic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UserDto User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubjectDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SubjectDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short SubjectIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private bool DeletedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short SubjectId {
            get {
                return this.SubjectIdField;
            }
            set {
                if ((this.SubjectIdField.Equals(value) != true)) {
                    this.SubjectIdField = value;
                    this.RaisePropertyChanged("SubjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CareerDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CareerDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CareerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private bool DeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.FacultyDto FacultyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UserCareerDto UserCareerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CareerId {
            get {
                return this.CareerIdField;
            }
            set {
                if ((this.CareerIdField.Equals(value) != true)) {
                    this.CareerIdField = value;
                    this.RaisePropertyChanged("CareerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.FacultyDto Faculty {
            get {
                return this.FacultyField;
            }
            set {
                if ((object.ReferenceEquals(this.FacultyField, value) != true)) {
                    this.FacultyField = value;
                    this.RaisePropertyChanged("Faculty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UserCareerDto UserCareer {
            get {
                return this.UserCareerField;
            }
            set {
                if ((object.ReferenceEquals(this.UserCareerField, value) != true)) {
                    this.UserCareerField = value;
                    this.RaisePropertyChanged("UserCareer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacultyDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FacultyDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short FacultyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private bool DeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.CareerDto CareerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short FacultyId {
            get {
                return this.FacultyIdField;
            }
            set {
                if ((this.FacultyIdField.Equals(value) != true)) {
                    this.FacultyIdField = value;
                    this.RaisePropertyChanged("FacultyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.CareerDto Career {
            get {
                return this.CareerField;
            }
            set {
                if ((object.ReferenceEquals(this.CareerField, value) != true)) {
                    this.CareerField = value;
                    this.RaisePropertyChanged("Career");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryAcademicDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CategoryAcademicDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private byte CategoryAcademicIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private bool DeletedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte CategoryAcademicId {
            get {
                return this.CategoryAcademicIdField;
            }
            set {
                if ((this.CategoryAcademicIdField.Equals(value) != true)) {
                    this.CategoryAcademicIdField = value;
                    this.RaisePropertyChanged("CategoryAcademicId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        private bool DeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.RoleDto RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.PersonDto PersonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.RoleDto Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.PersonDto Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RoleDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short RoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private bool DeletedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PersonDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long PersonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        private System.Nullable<System.DateTime> BirthDayField;
        
        private bool DeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.GenderDto GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UserDto UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long PersonId {
            get {
                return this.PersonIdField;
            }
            set {
                if ((this.PersonIdField.Equals(value) != true)) {
                    this.PersonIdField = value;
                    this.RaisePropertyChanged("PersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> BirthDay {
            get {
                return this.BirthDayField;
            }
            set {
                if ((this.BirthDayField.Equals(value) != true)) {
                    this.BirthDayField = value;
                    this.RaisePropertyChanged("BirthDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.GenderDto Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UserDto User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenderDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GenderDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private byte GenderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte GenderId {
            get {
                return this.GenderIdField;
            }
            set {
                if ((this.GenderIdField.Equals(value) != true)) {
                    this.GenderIdField = value;
                    this.RaisePropertyChanged("GenderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserCareerDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserCareerDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long UserCareerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UserDto UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.CareerDto CareerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long UserCareerId {
            get {
                return this.UserCareerIdField;
            }
            set {
                if ((this.UserCareerIdField.Equals(value) != true)) {
                    this.UserCareerIdField = value;
                    this.RaisePropertyChanged("UserCareerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UserDto User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.CareerDto Career {
            get {
                return this.CareerField;
            }
            set {
                if ((object.ReferenceEquals(this.CareerField, value) != true)) {
                    this.CareerField = value;
                    this.RaisePropertyChanged("Career");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePublicationMatterCareerFaculty.WebPublicationMatterCareerFacultyS" +
        "ervicesSoap")]
    public interface WebPublicationMatterCareerFacultyServicesSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento publicationMatterCareerFacultyDto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.InsertResponse Insert(Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.InsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        System.Threading.Tasks.Task<Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.InsertResponse> InsertAsync(Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.InsertRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento publicationMatterCareerFacultyDto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UpdateResponse Update(Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UpdateResponse> UpdateAsync(Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UpdateRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.GetResponse Get(Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        System.Threading.Tasks.Task<Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.GetResponse> GetAsync(Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.GetRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert", Namespace="http://tempuri.org/", Order=0)]
        public Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.InsertRequestBody Body;
        
        public InsertRequest() {
        }
        
        public InsertRequest(Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.InsertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.PublicationMatterCareerFacultyDto publicationMatterCareerFacultyDto;
        
        public InsertRequestBody() {
        }
        
        public InsertRequestBody(Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.PublicationMatterCareerFacultyDto publicationMatterCareerFacultyDto) {
            this.publicationMatterCareerFacultyDto = publicationMatterCareerFacultyDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertResponse", Namespace="http://tempuri.org/", Order=0)]
        public Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.InsertResponseBody Body;
        
        public InsertResponse() {
        }
        
        public InsertResponse(Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.InsertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertResponseBody {
        
        public InsertResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.PublicationMatterCareerFacultyDto publicationMatterCareerFacultyDto;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.PublicationMatterCareerFacultyDto publicationMatterCareerFacultyDto) {
            this.publicationMatterCareerFacultyDto = publicationMatterCareerFacultyDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateResponseBody {
        
        public UpdateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get", Namespace="http://tempuri.org/", Order=0)]
        public Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.GetRequestBody Body;
        
        public GetRequest() {
        }
        
        public GetRequest(Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.GetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetRequestBody() {
        }
        
        public GetRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResponse", Namespace="http://tempuri.org/", Order=0)]
        public Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.GetResponseBody Body;
        
        public GetResponse() {
        }
        
        public GetResponse(Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.GetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.PublicationMatterCareerFacultyDto GetResult;
        
        public GetResponseBody() {
        }
        
        public GetResponseBody(Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.PublicationMatterCareerFacultyDto GetResult) {
            this.GetResult = GetResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebPublicationMatterCareerFacultyServicesSoapChannel : Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.WebPublicationMatterCareerFacultyServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebPublicationMatterCareerFacultyServicesSoapClient : System.ServiceModel.ClientBase<Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.WebPublicationMatterCareerFacultyServicesSoap>, Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.WebPublicationMatterCareerFacultyServicesSoap {
        
        public WebPublicationMatterCareerFacultyServicesSoapClient() {
        }
        
        public WebPublicationMatterCareerFacultyServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebPublicationMatterCareerFacultyServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebPublicationMatterCareerFacultyServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebPublicationMatterCareerFacultyServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.InsertResponse Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.WebPublicationMatterCareerFacultyServicesSoap.Insert(Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.InsertRequest request) {
            return base.Channel.Insert(request);
        }
        
        public void Insert(Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.PublicationMatterCareerFacultyDto publicationMatterCareerFacultyDto) {
            Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.InsertRequest inValue = new Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.InsertRequest();
            inValue.Body = new Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.InsertRequestBody();
            inValue.Body.publicationMatterCareerFacultyDto = publicationMatterCareerFacultyDto;
            Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.InsertResponse retVal = ((Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.WebPublicationMatterCareerFacultyServicesSoap)(this)).Insert(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.InsertResponse> Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.WebPublicationMatterCareerFacultyServicesSoap.InsertAsync(Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.InsertRequest request) {
            return base.Channel.InsertAsync(request);
        }
        
        public System.Threading.Tasks.Task<Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.InsertResponse> InsertAsync(Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.PublicationMatterCareerFacultyDto publicationMatterCareerFacultyDto) {
            Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.InsertRequest inValue = new Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.InsertRequest();
            inValue.Body = new Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.InsertRequestBody();
            inValue.Body.publicationMatterCareerFacultyDto = publicationMatterCareerFacultyDto;
            return ((Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.WebPublicationMatterCareerFacultyServicesSoap)(this)).InsertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UpdateResponse Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.WebPublicationMatterCareerFacultyServicesSoap.Update(Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public void Update(Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.PublicationMatterCareerFacultyDto publicationMatterCareerFacultyDto) {
            Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UpdateRequest inValue = new Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UpdateRequest();
            inValue.Body = new Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UpdateRequestBody();
            inValue.Body.publicationMatterCareerFacultyDto = publicationMatterCareerFacultyDto;
            Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UpdateResponse retVal = ((Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.WebPublicationMatterCareerFacultyServicesSoap)(this)).Update(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UpdateResponse> Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.WebPublicationMatterCareerFacultyServicesSoap.UpdateAsync(Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UpdateResponse> UpdateAsync(Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.PublicationMatterCareerFacultyDto publicationMatterCareerFacultyDto) {
            Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UpdateRequest inValue = new Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UpdateRequest();
            inValue.Body = new Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.UpdateRequestBody();
            inValue.Body.publicationMatterCareerFacultyDto = publicationMatterCareerFacultyDto;
            return ((Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.WebPublicationMatterCareerFacultyServicesSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.GetResponse Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.WebPublicationMatterCareerFacultyServicesSoap.Get(Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.GetRequest request) {
            return base.Channel.Get(request);
        }
        
        public Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.PublicationMatterCareerFacultyDto Get(int id) {
            Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.GetRequest inValue = new Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.GetRequest();
            inValue.Body = new Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.GetRequestBody();
            inValue.Body.id = id;
            Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.GetResponse retVal = ((Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.WebPublicationMatterCareerFacultyServicesSoap)(this)).Get(inValue);
            return retVal.Body.GetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.GetResponse> Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.WebPublicationMatterCareerFacultyServicesSoap.GetAsync(Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.GetRequest request) {
            return base.Channel.GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.GetResponse> GetAsync(int id) {
            Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.GetRequest inValue = new Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.GetRequest();
            inValue.Body = new Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.GetRequestBody();
            inValue.Body.id = id;
            return ((Univalle.Fie.Sistemas.UniBook.UniTestAcademic.ServiceReferencePublicationMatterCareerFaculty.WebPublicationMatterCareerFacultyServicesSoap)(this)).GetAsync(inValue);
        }
    }
}
