//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuestionsService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuestionsDto", Namespace="http://tempuri.org/")]
    public partial class QuestionsDto : object
    {
        
        private long QuestionsIdField;
        
        private string TitleField;
        
        private string ContentField;
        
        private short PointsField;
        
        private bool SolvedField;
        
        private bool DeletedField;
        
        private WebQuestionsService.CategoryDto CategoryField;
        
        private WebQuestionsService.AnswerDto AnswerField;
        
        private WebQuestionsService.UserDto UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long QuestionsId
        {
            get
            {
                return this.QuestionsIdField;
            }
            set
            {
                this.QuestionsIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public short Points
        {
            get
            {
                return this.PointsField;
            }
            set
            {
                this.PointsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool Solved
        {
            get
            {
                return this.SolvedField;
            }
            set
            {
                this.SolvedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public WebQuestionsService.CategoryDto Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public WebQuestionsService.AnswerDto Answer
        {
            get
            {
                return this.AnswerField;
            }
            set
            {
                this.AnswerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public WebQuestionsService.UserDto User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryDto", Namespace="http://tempuri.org/")]
    public partial class CategoryDto : object
    {
        
        private short CategoryIdField;
        
        private string NameField;
        
        private string PurposeField;
        
        private WebQuestionsService.QuestionsDto QuestionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short CategoryId
        {
            get
            {
                return this.CategoryIdField;
            }
            set
            {
                this.CategoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Purpose
        {
            get
            {
                return this.PurposeField;
            }
            set
            {
                this.PurposeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WebQuestionsService.QuestionsDto Questions
        {
            get
            {
                return this.QuestionsField;
            }
            set
            {
                this.QuestionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnswerDto", Namespace="http://tempuri.org/")]
    public partial class AnswerDto : object
    {
        
        private long AnswerIdField;
        
        private string ContentField;
        
        private short PointsField;
        
        private bool SolvedField;
        
        private bool DeletedField;
        
        private WebQuestionsService.QuestionsDto QuestionsField;
        
        private WebQuestionsService.UserDto UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long AnswerId
        {
            get
            {
                return this.AnswerIdField;
            }
            set
            {
                this.AnswerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short Points
        {
            get
            {
                return this.PointsField;
            }
            set
            {
                this.PointsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Solved
        {
            get
            {
                return this.SolvedField;
            }
            set
            {
                this.SolvedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public WebQuestionsService.QuestionsDto Questions
        {
            get
            {
                return this.QuestionsField;
            }
            set
            {
                this.QuestionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public WebQuestionsService.UserDto User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDto", Namespace="http://tempuri.org/")]
    public partial class UserDto : object
    {
        
        private long UserIdField;
        
        private string EmailField;
        
        private WebQuestionsService.PasswordDto PasswordField;
        
        private bool DeletedField;
        
        private WebQuestionsService.RoleDto RoleField;
        
        private WebQuestionsService.UserCareerDto UserCareerField;
        
        private WebQuestionsService.PersonDto PersonField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public WebQuestionsService.PasswordDto Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public WebQuestionsService.RoleDto Role
        {
            get
            {
                return this.RoleField;
            }
            set
            {
                this.RoleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public WebQuestionsService.UserCareerDto UserCareer
        {
            get
            {
                return this.UserCareerField;
            }
            set
            {
                this.UserCareerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public WebQuestionsService.PersonDto Person
        {
            get
            {
                return this.PersonField;
            }
            set
            {
                this.PersonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordDto", Namespace="http://tempuri.org/")]
    public partial class PasswordDto : object
    {
        
        private long PasswordIdField;
        
        private string PswField;
        
        private System.DateTime DateField;
        
        private byte StateField;
        
        private string NewPasswordField;
        
        private long UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long PasswordId
        {
            get
            {
                return this.PasswordIdField;
            }
            set
            {
                this.PasswordIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Psw
        {
            get
            {
                return this.PswField;
            }
            set
            {
                this.PswField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public byte State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NewPassword
        {
            get
            {
                return this.NewPasswordField;
            }
            set
            {
                this.NewPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public long UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleDto", Namespace="http://tempuri.org/")]
    public partial class RoleDto : object
    {
        
        private short RoleIdField;
        
        private string NameField;
        
        private bool DeletedField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short RoleId
        {
            get
            {
                return this.RoleIdField;
            }
            set
            {
                this.RoleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserCareerDto", Namespace="http://tempuri.org/")]
    public partial class UserCareerDto : object
    {
        
        private long UserCareerIdField;
        
        private WebQuestionsService.UserDto UserField;
        
        private WebQuestionsService.CareerDto CareerField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long UserCareerId
        {
            get
            {
                return this.UserCareerIdField;
            }
            set
            {
                this.UserCareerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public WebQuestionsService.UserDto User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public WebQuestionsService.CareerDto Career
        {
            get
            {
                return this.CareerField;
            }
            set
            {
                this.CareerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonDto", Namespace="http://tempuri.org/")]
    public partial class PersonDto : object
    {
        
        private long PersonIdField;
        
        private string NameField;
        
        private string LastNameField;
        
        private System.Nullable<System.DateTime> BirthDayField;
        
        private bool DeletedField;
        
        private WebQuestionsService.GenderDto GenderField;
        
        private WebQuestionsService.UserDto UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long PersonId
        {
            get
            {
                return this.PersonIdField;
            }
            set
            {
                this.PersonIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> BirthDay
        {
            get
            {
                return this.BirthDayField;
            }
            set
            {
                this.BirthDayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public WebQuestionsService.GenderDto Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public WebQuestionsService.UserDto User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CareerDto", Namespace="http://tempuri.org/")]
    public partial class CareerDto : object
    {
        
        private int CareerIdField;
        
        private string NameField;
        
        private bool DeletedField;
        
        private WebQuestionsService.FacultyDto FacultyField;
        
        private WebQuestionsService.UserCareerDto UserCareerField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CareerId
        {
            get
            {
                return this.CareerIdField;
            }
            set
            {
                this.CareerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public WebQuestionsService.FacultyDto Faculty
        {
            get
            {
                return this.FacultyField;
            }
            set
            {
                this.FacultyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public WebQuestionsService.UserCareerDto UserCareer
        {
            get
            {
                return this.UserCareerField;
            }
            set
            {
                this.UserCareerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacultyDto", Namespace="http://tempuri.org/")]
    public partial class FacultyDto : object
    {
        
        private short FacultyIdField;
        
        private string NameField;
        
        private bool DeletedField;
        
        private WebQuestionsService.CareerDto CareerField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short FacultyId
        {
            get
            {
                return this.FacultyIdField;
            }
            set
            {
                this.FacultyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public WebQuestionsService.CareerDto Career
        {
            get
            {
                return this.CareerField;
            }
            set
            {
                this.CareerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenderDto", Namespace="http://tempuri.org/")]
    public partial class GenderDto : object
    {
        
        private short GenderIdField;
        
        private string NameField;
        
        private WebQuestionsService.PersonDto PersonField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short GenderId
        {
            get
            {
                return this.GenderIdField;
            }
            set
            {
                this.GenderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WebQuestionsService.PersonDto Person
        {
            get
            {
                return this.PersonField;
            }
            set
            {
                this.PersonField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebQuestionsService.WebQuestionsServiceSoap")]
    public interface WebQuestionsServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        System.Threading.Tasks.Task<WebQuestionsService.GetResponse> GetAsync(WebQuestionsService.GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        System.Threading.Tasks.Task<WebQuestionsService.InsertResponse> InsertAsync(WebQuestionsService.InsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<WebQuestionsService.UpdateResponse> UpdateAsync(WebQuestionsService.UpdateRequest request);

        // CODEGEN: Generating message contract since element name GetResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/Get", ReplyAction = "*")]
        WebQuestionsService.GetResponse Get(WebQuestionsService.GetRequest request);

        // CODEGEN: Generating message contract since element name roleDto from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/Insert", ReplyAction = "*")]
        WebQuestionsService.InsertResponse Insert(WebQuestionsService.InsertRequest request);

        // CODEGEN: Generating message contract since element name roleDto from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/Update", ReplyAction = "*")]
        WebQuestionsService.UpdateResponse Update(WebQuestionsService.UpdateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get", Namespace="http://tempuri.org/", Order=0)]
        public WebQuestionsService.GetRequestBody Body;
        
        public GetRequest()
        {
        }
        
        public GetRequest(WebQuestionsService.GetRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public GetRequestBody()
        {
        }
        
        public GetRequestBody(long id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebQuestionsService.GetResponseBody Body;
        
        public GetResponse()
        {
        }
        
        public GetResponse(WebQuestionsService.GetResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebQuestionsService.QuestionsDto GetResult;
        
        public GetResponseBody()
        {
        }
        
        public GetResponseBody(WebQuestionsService.QuestionsDto GetResult)
        {
            this.GetResult = GetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert", Namespace="http://tempuri.org/", Order=0)]
        public WebQuestionsService.InsertRequestBody Body;
        
        public InsertRequest()
        {
        }
        
        public InsertRequest(WebQuestionsService.InsertRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebQuestionsService.QuestionsDto questionsDto;
        
        public InsertRequestBody()
        {
        }
        
        public InsertRequestBody(WebQuestionsService.QuestionsDto questionsDto)
        {
            this.questionsDto = questionsDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebQuestionsService.InsertResponseBody Body;
        
        public InsertResponse()
        {
        }
        
        public InsertResponse(WebQuestionsService.InsertResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertResponseBody
    {
        
        public InsertResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public WebQuestionsService.UpdateRequestBody Body;
        
        public UpdateRequest()
        {
        }
        
        public UpdateRequest(WebQuestionsService.UpdateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebQuestionsService.QuestionsDto questionsDto;
        
        public UpdateRequestBody()
        {
        }
        
        public UpdateRequestBody(WebQuestionsService.QuestionsDto questionsDto)
        {
            this.questionsDto = questionsDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebQuestionsService.UpdateResponseBody Body;
        
        public UpdateResponse()
        {
        }
        
        public UpdateResponse(WebQuestionsService.UpdateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateResponseBody
    {
        
        public UpdateResponseBody()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface WebQuestionsServiceSoapChannel : WebQuestionsService.WebQuestionsServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class WebQuestionsServiceSoapClient : System.ServiceModel.ClientBase<WebQuestionsService.WebQuestionsServiceSoap>, WebQuestionsService.WebQuestionsServiceSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebQuestionsServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebQuestionsServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), WebQuestionsServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebQuestionsServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebQuestionsServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebQuestionsServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebQuestionsServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebQuestionsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebQuestionsService.GetResponse> WebQuestionsService.WebQuestionsServiceSoap.GetAsync(WebQuestionsService.GetRequest request)
        {
            return base.Channel.GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebQuestionsService.GetResponse> GetAsync(short id)
        {
            WebQuestionsService.GetRequest inValue = new WebQuestionsService.GetRequest();
            inValue.Body = new WebQuestionsService.GetRequestBody();
            inValue.Body.id = id;
            return ((WebQuestionsService.WebQuestionsServiceSoap)(this)).GetAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebQuestionsService.GetResponse WebQuestionsService.WebQuestionsServiceSoap.Get(WebQuestionsService.GetRequest request)
        {
            return base.Channel.Get(request);
        }

        public WebQuestionsService.QuestionsDto Get(long id)
        {
            WebQuestionsService.GetRequest inValue = new WebQuestionsService.GetRequest();
            inValue.Body = new WebQuestionsService.GetRequestBody();
            inValue.Body.id = id;
            WebQuestionsService.GetResponse retVal = ((WebQuestionsService.WebQuestionsServiceSoap)(this)).Get(inValue);
            return retVal.Body.GetResult;
        }

        WebQuestionsService.InsertResponse WebQuestionsServiceSoap.Insert(WebQuestionsService.InsertRequest request)
        {
            return base.Channel.Insert(request);
        }

        public void Insert(WebQuestionsService.QuestionsDto questionsDto)
        {
            WebQuestionsService.InsertRequest inValue = new WebQuestionsService.InsertRequest();
            inValue.Body = new WebQuestionsService.InsertRequestBody();
            inValue.Body.questionsDto = questionsDto;
            WebQuestionsService.InsertResponse retVal = ((WebQuestionsService.WebQuestionsServiceSoap)(this)).Insert(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebQuestionsService.UpdateResponse WebQuestionsService.WebQuestionsServiceSoap.Update(WebQuestionsService.UpdateRequest request)
        {
            return base.Channel.Update(request);
        }

        public void Update(WebQuestionsService.QuestionsDto questionsDto)
        {
            WebQuestionsService.UpdateRequest inValue = new WebQuestionsService.UpdateRequest();
            inValue.Body = new WebQuestionsService.UpdateRequestBody();
            inValue.Body.questionsDto = questionsDto;
            WebQuestionsService.UpdateResponse retVal = ((WebQuestionsService.WebQuestionsServiceSoap)(this)).Update(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebQuestionsService.InsertResponse> WebQuestionsService.WebQuestionsServiceSoap.InsertAsync(WebQuestionsService.InsertRequest request)
        {
            return base.Channel.InsertAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebQuestionsService.InsertResponse> InsertAsync(WebQuestionsService.QuestionsDto questionsDto)
        {
            WebQuestionsService.InsertRequest inValue = new WebQuestionsService.InsertRequest();
            inValue.Body = new WebQuestionsService.InsertRequestBody();
            inValue.Body.questionsDto = questionsDto;
            return ((WebQuestionsService.WebQuestionsServiceSoap)(this)).InsertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebQuestionsService.UpdateResponse> WebQuestionsService.WebQuestionsServiceSoap.UpdateAsync(WebQuestionsService.UpdateRequest request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebQuestionsService.UpdateResponse> UpdateAsync(WebQuestionsService.QuestionsDto questionsDto)
        {
            WebQuestionsService.UpdateRequest inValue = new WebQuestionsService.UpdateRequest();
            inValue.Body = new WebQuestionsService.UpdateRequestBody();
            inValue.Body.questionsDto = questionsDto;
            return ((WebQuestionsService.WebQuestionsServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebQuestionsServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebQuestionsServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebQuestionsServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:29357/WebQuestionsService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebQuestionsServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:29357/WebQuestionsService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebQuestionsServiceSoap,
            
            WebQuestionsServiceSoap12,
        }
    }
}
